// Replace with your request types
export const APPLICATION_GET_LIST = "APPLICATION_GET_LIST";
export const APPLICATION_CREATE = "APPLICATION_CREATE";
export const APPLICATION_UPDATE = "APPLICATION_UPDATE";
export const APPLICATION_GET_ONE = "APPLICATION_GET_ONE";
export const APPLICATION_API_SUCCESS = "APPLICATION_API_SUCCESS";
export const APPLICATION_API_ERROR = "APPLICATION_API_ERROR";
export const APPLICATION_DELETE = "APPLICATION_DELETE";
export const TAB_INDEX = "TAB_INDEX";
