// Replace with your request types
export const LICENSETYPE_GET_LIST = "LICENSETYPE_GET_LIST";
export const LICENSETYPE_CREATE = "LICENSETYPE_CREATE";
export const LICENSETYPE_UPDATE = "LICENSETYPE_UPDATE";
export const LICENSETYPE_GET_ONE = "LICENSETYPE_GET_ONE";
export const LICENSETYPE_DELETE = "LICENSETYPE_DELETE";
export const LICENSETYPE_REMOVE_ONE = "LICENSETYPE_REMOVE_ONE";
export const LICENSETYPE_API_SUCCESS = "LICENSETYPE_API_SUCCESS";
export const LICENSETYPE_API_ERROR = "LICENSETYPE_API_ERROR";
