// Replace with your request types
export const PACKAGE_GET_LIST = "PACKAGE_GET_LIST";
export const PACKAGE_CREATE = "PACKAGE_CREATE";
export const PACKAGE_UPDATE = "PACKAGE_UPDATE";
export const PACKAGE_GET_ONE = "PACKAGE_GET_ONE";
export const PACKAGE_DELETE = "PACKAGE_DELETE";
export const PACKAGE_API_SUCCESS = "PACKAGE_API_SUCCESS";
export const PACKAGE_API_ERROR = "PACKAGE_API_ERROR";
