// Replace with your request types
export const FEATURE_GET_LIST = "FEATURE_GET_LIST";
export const FEATURE_CREATE = "FEATURE_CREATE";
export const FEATURE_UPDATE = "FEATURE_UPDATE";
export const FEATURE_DELETE = "FEATURE_DELETE";
export const FEATURE_GET_ONE = "FEATURE_GET_ONE";
export const FEATURE_API_SUCCESS = "FEATURE_API_SUCCESS";
export const FEATURE_API_ERROR = "FEATURE_API_ERROR";
